"""Standard default regulation parameters used in the SACVA calculations."""

reg_params = {
    'd457': {
        'level': ['risk_factor', 'bucket', 'total', 'RWLabel', 'tranche'],
        'scenario': ['medium', 'low', 'high'],
        'measure': ['ws', 'sb', 'kb^2', 'kb', 'alt_sb', 'k', 'alt_flag', 'xb', 'x', 'ssb', 'ss',
                    'cvru', 'cvrd', 'sbu', 'sbd', 'kbu', 'kbd', 'xbu', 'xbd', 'ssbu', 'ssbd',
                    'net_jtd_s', 'net_jtd_l', 'w_net_jtd_l', 'hbr', 'drc', 'ScaledJTD'
                    ],
        'scenario_measure': ['kb', 'alt_sb', 'kb^2', 'k', 'alt_flag', 'xb', 'x', 'kbu', 'kbd', 'xbu', 'xbd', 'sb',
                             'ss', 'ssb', 'ssbu', 'ssbd'],
        'total_measure': ['k', 'x', 'alt_flag', 'ws', 'cvru', 'cvrd', 'net_jtd_s', 'net_jtd_l', 'w_net_jtd_l',
                          'w_net_jtd_s', 'drc', 'RRAO', 'ss'],
        'bucket_measure': ['net_jtd_s', 'net_jtd_l', 'w_net_jtd_l', 'w_net_jtd_s', 'hbr', 'drc'],
        'aggregation_measure': ['ws', 'cvru', 'cvrd', 'sbu', 'sbd'],
        'risk_factor_measure': ['net_jtd_s', 'net_jtd_l', 'w_net_jtd_l', 'w_net_jtd_s', 'RiskWeightValue', 'ScaledJTD',
                                'hbr', 'drc'],
        'risk_factor_tranche': ['ScaledJTD'],
        'RWLabel_measure': ['RRAO'],
        'sa.drc.ZeroRiskIncludeInHBR': 'Y',
        'sa.fx.divider.enabled': 'y',
        'sa.fx.divider.value': 1.5,
        'sa.aggregation.bucketcode': 'N',
        'sa.fx.otherSector': None,
        'sa.commodity.otherSector': None,
        'sa.girr.otherSector': None,
        'sa.equity.otherSector': 11,
        'sa.csrsec.otherSector': 25,
        'sa.csrnonsec.otherSector': 16,
        'sa.rrao.netting.enabled': 'Y',
        'sa.CurvatureFlag': 'N'
    },
    'crr2': {
        'level': ['risk_factor', 'bucket', 'total', 'RWLabel', 'tranche'],
        'scenario': ['medium', 'low', 'high'],
        'measure': ['ws', 'sb', 'kb^2', 'kb', 'alt_sb', 'k', 'alt_flag', 'xb', 'x', 'ssb', 'ss',
                    'cvru', 'cvrd', 'sbu', 'sbd', 'kbu', 'kbd', 'xbu', 'xbd', 'ssbu', 'ssbd',
                    'net_jtd_s', 'net_jtd_l', 'w_net_jtd_l', 'hbr', 'drc', 'ScaledJTD'
                    ],
        'scenario_measure': ['kb', 'alt_sb', 'kb^2', 'k', 'alt_flag', 'xb', 'x', 'kbu', 'kbd', 'xbu', 'xbd', 'sb',
                             'ss', 'ssb', 'ssbu', 'ssbd'],
        'total_measure': ['k', 'x', 'alt_flag', 'ws', 'cvru', 'cvrd', 'net_jtd_s', 'net_jtd_l', 'w_net_jtd_l',
                          'w_net_jtd_s', 'drc', 'RRAO', 'ss'],
        'bucket_measure': ['net_jtd_s', 'net_jtd_l', 'w_net_jtd_l', 'w_net_jtd_s', 'hbr', 'drc'],
        'aggregation_measure': ['ws', 'cvru', 'cvrd', 'sbu', 'sbd'],
        'risk_factor_measure': ['net_jtd_s', 'net_jtd_l', 'w_net_jtd_l', 'w_net_jtd_s', 'RiskWeightValue', 'ScaledJTD',
                                'hbr', 'drc'],
        'risk_factor_tranche': ['ScaledJTD'],
        'RWLabel_measure': ['RRAO'],
        'sa.drc.ZeroRiskIncludeInHBR': 'Y',
        'sa.fx.divider.enabled': 'y',
        'sa.fx.divider.value': 1.5,
        'sa.aggregation.bucketcode': 'N',
        'sa.fx.otherSector': None,
        'sa.commodity.otherSector': None,
        'sa.girr.otherSector': None,
        'sa.equity.otherSector': 11,
        'sa.csrsec.otherSector': 25,
        'sa.csrnonsec.otherSector': 18,
        'sa.rrao.netting.enabled': 'Y',
        'sa.CurvatureFlag': 'N'
    }
}
